# Generated by Django 5.0.9 on 2024-10-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_genre_genre_name_case_insensitive_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provideer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=200)),
                ('orderNumber', models.CharField(help_text='ex. 000000000', max_length=13, unique=True, verbose_name='orderNumber')),
                ('inspector', models.CharField(max_length=200)),
                ('inspectionDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['companyName', 'inspectionDate'],
            },
        ),
    ]
